export default function DocsPreview() {
  return (
<div aria-label="CS Docs business management interface preview" className="product-ui docs-ui docs-product-ui service-media-slot">
<div className="docs-product-shell">
<aside className="docs-product-sidebar">
<div className="docs-product-brand"><cs-brand-logo aria-hidden="true" label="" state="docs"></cs-brand-logo><span><strong>CS Docs</strong><small>Northstar Trading</small></span></div>
<nav aria-label="CS Docs modules" className="docs-product-nav">
<button className="is-active" data-docs-view="invoices" type="button"><i>▤</i><span><b>Invoices</b><small>Billing & payments</small></span></button>
<button data-docs-view="payroll" type="button"><i>⌁</i><span><b>Payroll</b><small>Employees & runs</small></span></button>
<button data-docs-view="inventory" type="button"><i>◇</i><span><b>Inventory</b><small>Stock & items</small></span></button>
</nav>
<div className="docs-product-side-label">WORKSPACE</div>
<div className="docs-product-side-links"><span>Customers</span><span>Employees</span><span>Products</span></div>
<div className="docs-product-profile"><i>AK</i><span><b>Alex Karim</b><small>Administrator</small></span><em>•••</em></div>
</aside>
<section className="docs-product-main">
<header className="docs-product-topbar"><div className="docs-product-path"><span>CS Docs</span><i>/</i><b data-docs-title="">Invoices</b></div><div className="docs-product-tools"><button className="docs-tool-search" type="button">⌕ <span>Search</span></button><button className="docs-tool-notify" aria-label="Notifications" type="button">♢<i></i></button><button className="docs-create-record" data-docs-create="" type="button">+ New invoice</button></div></header>
<div className="docs-product-view is-active" data-docs-panel="invoices">
<div className="docs-product-heading"><div><span className="docs-product-eyebrow">INVOICING</span><h4>Know what has been billed and what still needs attention.</h4><p>Create invoices, follow payment status, and keep recent billing activity easy to review.</p></div><div className="docs-period-pill"><span>October 2026</span><button type="button">⌄</button></div></div>
<div className="docs-product-stats">
<article><span>Outstanding</span><strong>$24,860</strong><small><i className="up">↑ 8.4%</i> from last month</small></article>
<article><span>Paid this month</span><strong>$38,420</strong><small>17 invoices settled</small></article>
<article><span>Overdue</span><strong>$4,280</strong><small><i className="warn">3 invoices</i> need follow-up</small></article>
</div>
<div className="docs-product-dashboard docs-invoice-dashboard">
<section className="docs-product-card docs-revenue-card"><div className="docs-product-card-head"><span><small>PAYMENTS</small><b>Collected this month</b></span><em>$38.4k</em></div><div className="docs-mini-chart" aria-hidden="true"><span style={{ '--h': '38%' }}></span><span style={{ '--h': '54%' }}></span><span style={{ '--h': '42%' }}></span><span style={{ '--h': '68%' }}></span><span style={{ '--h': '61%' }}></span><span style={{ '--h': '83%' }}></span><span style={{ '--h': '72%' }}></span><span style={{ '--h': '92%' }}></span><i></i></div><div className="docs-chart-axis"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div></section>
<section className="docs-product-card docs-attention-card"><div className="docs-product-card-head"><span><small>NEEDS ATTENTION</small><b>Billing follow-up</b></span><button type="button">View all</button></div><div className="docs-attention-list"><div><i className="danger">!</i><span><b>INV-1034 · Meridian Co.</b><small>Overdue by 8 days</small></span><strong>$2,140</strong></div><div><i>•</i><span><b>INV-1042 · Nora Labs</b><small>Draft · updated today</small></span><strong>$1,860</strong></div><div><i className="success">✓</i><span><b>INV-1040 · Orion Freight</b><small>Paid this morning</small></span><strong>$3,920</strong></div></div></section>
</div>
<section className="docs-product-card docs-record-table"><div className="docs-product-card-head"><span><small>RECENT INVOICES</small><b>Latest billing records</b></span><button type="button">All invoices →</button></div><div className="docs-prod-row docs-prod-row-head"><span>Invoice</span><span>Customer</span><span>Issued</span><span>Amount</span><span>Status</span></div><div className="docs-prod-row"><span><b>INV-1042</b></span><span>Nora Labs</span><span>06 Oct</span><span><b>$1,860</b></span><span><em className="draft">Draft</em></span></div><div className="docs-prod-row"><span><b>INV-1041</b></span><span>North & Pine</span><span>05 Oct</span><span><b>$2,480</b></span><span><em className="sent">Sent</em></span></div><div className="docs-prod-row"><span><b>INV-1040</b></span><span>Orion Freight</span><span>02 Oct</span><span><b>$3,920</b></span><span><em className="paid">Paid</em></span></div></section>
</div>
<div className="docs-product-view" data-docs-panel="payroll" hidden>
<div className="docs-product-heading"><div><span className="docs-product-eyebrow">PAYROLL</span><h4>Prepare each payroll run with the numbers in front of you.</h4><p>Review employees, gross pay, deductions, and the status of the next payroll before you process it.</p></div><div className="docs-period-pill"><span>October payroll</span><button type="button">⌄</button></div></div>
<div className="docs-product-stats"><article><span>Employees</span><strong>24</strong><small>23 active · 1 on leave</small></article><article><span>Gross payroll</span><strong>$18,420</strong><small>Current pay period</small></article><article><span>Pay date</span><strong>28 Oct</strong><small><i className="up">Ready</i> for review</small></article></div>
<div className="docs-payroll-run"><div className="docs-payroll-progress"><div className="docs-run-ring"><strong>82%</strong><small>ready</small></div><span><small>UPCOMING RUN</small><b>October payroll</b><em>20 of 24 employee records checked</em></span></div><div className="docs-run-checks"><div><i>✓</i><span><b>Employee details</b><small>Complete</small></span></div><div><i>✓</i><span><b>Salary entries</b><small>Complete</small></span></div><div className="warning"><i>!</i><span><b>4 records</b><small>Need review</small></span></div></div><button type="button">Review payroll</button></div>
<section className="docs-product-card docs-record-table payroll-record-table"><div className="docs-product-card-head"><span><small>EMPLOYEES</small><b>Current payroll records</b></span><button type="button">View employees →</button></div><div className="docs-prod-row docs-prod-row-head"><span>Employee</span><span>Role</span><span>Gross pay</span><span>Deductions</span><span>Status</span></div><div className="docs-prod-row"><span className="docs-person"><i>AK</i><b>Aisha Khan</b></span><span>Operations</span><span><b>$1,180</b></span><span>$120</span><span><em className="paid">Ready</em></span></div><div className="docs-prod-row"><span className="docs-person"><i>OR</i><b>Omar Reed</b></span><span>Sales</span><span><b>$1,420</b></span><span>$160</span><span><em className="paid">Ready</em></span></div><div className="docs-prod-row"><span className="docs-person"><i>LM</i><b>Lina Malik</b></span><span>Support</span><span><b>$1,090</b></span><span>$90</span><span><em className="draft">Review</em></span></div></section>
</div>
<div className="docs-product-view" data-docs-panel="inventory" hidden>
<div className="docs-product-heading"><div><span className="docs-product-eyebrow">INVENTORY</span><h4>See what is in stock before low quantities become a problem.</h4><p>Maintain product quantities, spot items running low, and review the latest stock records from one inventory view.</p></div><div className="docs-period-pill"><span>All locations</span><button type="button">⌄</button></div></div>
<div className="docs-product-stats"><article><span>Inventory value</span><strong>$91,240</strong><small>1,842 units recorded</small></article><article><span>Low stock</span><strong>12</strong><small><i className="warn">Needs attention</i></small></article><article><span>Products</span><strong>286</strong><small>18 categories</small></article></div>
<div className="docs-product-dashboard inventory-overview-grid"><section className="docs-product-card"><div className="docs-product-card-head"><span><small>STOCK HEALTH</small><b>Items by stock level</b></span><em>286 products</em></div><div className="docs-stock-health"><div><span><b>Healthy stock</b><small>244 products</small></span><em><i style={{ '--stock': '85%' }}></i></em><strong>85%</strong></div><div><span><b>Low stock</b><small>30 products</small></span><em><i className="low" style={{ '--stock': '48%' }}></i></em><strong className="low">10%</strong></div><div><span><b>Critical</b><small>12 products</small></span><em><i className="critical" style={{ '--stock': '22%' }}></i></em><strong className="critical">5%</strong></div></div></section><section className="docs-product-card"><div className="docs-product-card-head"><span><small>REORDER</small><b>Items to check</b></span><button type="button">View all</button></div><div className="docs-reorder-list"><div><i className="thumb-one"></i><span><b>USB-C Hub</b><small>4 units remaining</small></span><em>Reorder</em></div><div><i className="thumb-two"></i><span><b>Desk Stand</b><small>7 units remaining</small></span><em>Reorder</em></div><div><i className="thumb-three"></i><span><b>Wireless Mouse</b><small>9 units remaining</small></span><em>Review</em></div></div></section></div>
<section className="docs-product-card docs-record-table inventory-record-table"><div className="docs-product-card-head"><span><small>PRODUCTS</small><b>Recent inventory records</b></span><button type="button">All products →</button></div><div className="docs-prod-row docs-prod-row-head"><span>Product</span><span>SKU</span><span>On hand</span><span>Reorder at</span><span>Status</span></div><div className="docs-prod-row"><span><b>USB-C Hub</b></span><span>ACC-204</span><span><b>4</b></span><span>12</span><span><em className="overdue">Critical</em></span></div><div className="docs-prod-row"><span><b>Desk Stand</b></span><span>DSK-118</span><span><b>7</b></span><span>10</span><span><em className="draft">Low</em></span></div><div className="docs-prod-row"><span><b>Notebook Set</b></span><span>STA-072</span><span><b>84</b></span><span>20</span><span><em className="paid">Healthy</em></span></div></section>
</div>
</section>
</div>
</div>
  );
}
